keys:
  - &kamino age1mm26m7q7u942g8653j5sflhzgr69vxatd4twajz2hdudl8tlx4gsdguext
  - &jakku  age1ghdr02tkr2vasp9nnf4z7sh6c3zg32l3upwf0qd7zmjaq34zpuhsdgy4rg

creation_rules:
  - path_regex: secrets/kamino/.*
    key_groups:
      - age: [*kamino]
  - path_regex: secrets/jakku/.*
    key_groups:
      - age: [*jakku]
